//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by openapi-gen. DO NOT EDIT.

package v3

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AlertException) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AlertException"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AlertExceptionList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AlertExceptionList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AlertExceptionSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AlertExceptionSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AlertExceptionStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AlertExceptionStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AllocationAttribute) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AllocationAttribute"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditEventsSelection) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuditEventsSelection"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditResource) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuditResource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditSummary) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuditSummary"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizationReview) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizationReview"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizationReviewList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizationReviewList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizationReviewResourceAttributes) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizationReviewResourceAttributes"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizationReviewSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizationReviewSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizationReviewStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizationReviewStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizedResourceGroup) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizedResourceGroup"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizedResourceVerb) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizedResourceVerb"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthorizedResourceVerbs) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AuthorizedResourceVerbs"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AutoHostEndpointConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.AutoHostEndpointConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BFDConfiguration) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BFDConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BFDConfigurationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BFDConfigurationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BFDConfigurationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BFDConfigurationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BFDInterface) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BFDInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPConfiguration) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPConfigurationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPConfigurationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPConfigurationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPConfigurationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPDaemonStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPDaemonStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilter) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilter"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterAddCommunity) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterAddCommunity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterCommunityMatch) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterCommunityMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterOperation) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterOperation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterPrefixLengthV4) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterPrefixLengthV4"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterPrefixLengthV6) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterPrefixLengthV6"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterPrependASPath) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterPrependASPath"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterRuleV4) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterRuleV4"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterRuleV6) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterRuleV6"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterSetPriority) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterSetPriority"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPFilterSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPFilterSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPPassword) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPPassword"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPPeer) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPPeer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPPeerList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPPeerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BGPPeerSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BGPPeerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BPFConntrackTimeouts) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BPFConntrackTimeouts"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BlockAffinity) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BlockAffinity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BlockAffinityList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BlockAffinityList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BlockAffinitySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.BlockAffinitySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkFilter) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkFilter"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkNode) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkNode"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkNodeSummary) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkNodeSummary"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkParams) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkParams"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkResult) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkResult"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkResultCount) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkResultCount"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkSectionResult) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkSectionResult"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkSelection) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkSelection"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CISBenchmarkSummary) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CISBenchmarkSummary"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeAgentStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeAgentStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeBGPRouteStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeBGPRouteStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeBGPStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeBGPStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodePeer) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodePeer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeRoute) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeRoute"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeRouteLearnedFrom) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeRouteLearnedFrom"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeStatusList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeStatusList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeStatusSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeStatusSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CalicoNodeStatusStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CalicoNodeStatusStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterInformation) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ClusterInformation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterInformationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ClusterInformationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterInformationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ClusterInformationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Community) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.Community"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CompletedReportJob) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.CompletedReportJob"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ControllersConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ControllersConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DPIActive) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DPIActive"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DPIErrorCondition) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DPIErrorCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DPINode) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DPINode"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DashboardData) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DashboardData"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DashboardLayout) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DashboardLayout"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeepPacketInspection) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DeepPacketInspection"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeepPacketInspectionList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DeepPacketInspectionList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeepPacketInspectionSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DeepPacketInspectionSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeepPacketInspectionStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DeepPacketInspectionStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DetectorParams) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.DetectorParams"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressGatewayPolicy) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EgressGatewayPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressGatewayPolicyDestinationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EgressGatewayPolicyDestinationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressGatewayPolicyList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EgressGatewayPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressGatewayPolicySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EgressGatewayPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressGatewayRule) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EgressGatewayRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressGatewaySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EgressGatewaySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EgressSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointPort) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EndpointPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointsReportEndpoint) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EndpointsReportEndpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointsReportFlow) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EndpointsReportFlow"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointsReportNamespace) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EndpointsReportNamespace"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointsReportService) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EndpointsReportService"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointsSelection) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EndpointsSelection"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointsSummary) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EndpointsSummary"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EntityRule) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EntityRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ErrorCondition) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ErrorCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EtcdConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.EtcdConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExternalNetwork) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ExternalNetwork"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExternalNetworkList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ExternalNetworkList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExternalNetworkSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ExternalNetworkSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FederatedServicesControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.FederatedServicesControllerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FelixConfiguration) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.FelixConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FelixConfigurationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.FelixConfigurationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FelixConfigurationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.FelixConfigurationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FlowEndpoint) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.FlowEndpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalAlert) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalAlert"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalAlertList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalAlertList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalAlertSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalAlertSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalAlertStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalAlertStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalAlertSubstitution) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalAlertSubstitution"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalAlertTemplate) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalAlertTemplate"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalAlertTemplateList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalAlertTemplateList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalNetworkPolicy) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalNetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalNetworkPolicyList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalNetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalNetworkPolicySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalNetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalNetworkSet) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalNetworkSet"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalNetworkSetList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalNetworkSetList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalNetworkSetSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalNetworkSetSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalNetworkSetSync) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalNetworkSetSync"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalReport) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalReport"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalReportList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalReportList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalReportType) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalReportType"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalReportTypeList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalReportTypeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalThreatFeed) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalThreatFeed"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalThreatFeedList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalThreatFeedList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalThreatFeedSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalThreatFeedSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GlobalThreatFeedStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.GlobalThreatFeedStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPHeader) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HTTPHeader"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPHeaderCriteria) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HTTPHeaderCriteria"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPHeaderSource) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HTTPHeaderSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPMatch) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HTTPMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPPath) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HTTPPath"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPPull) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HTTPPull"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HealthTimeoutOverride) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HealthTimeoutOverride"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostEndpoint) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HostEndpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostEndpointList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HostEndpointList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostEndpointSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.HostEndpointSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ICMPFields) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ICMPFields"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMBlock) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMBlock"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMBlockList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMBlockList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMBlockSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMBlockSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMConfiguration) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMConfigurationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMConfigurationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMConfigurationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMConfigurationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMHandle) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMHandle"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMHandleList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMHandleList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMHandleSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPAMHandleSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPIPConfiguration) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPIPConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPool) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPPool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPPoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPPoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPPoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPReservation) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPReservation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPReservationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPReservationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPReservationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.IPReservationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in KubeConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.KubeConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in KubeControllersConfiguration) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.KubeControllersConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in KubeControllersConfigurationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.KubeControllersConfigurationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in KubeControllersConfigurationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.KubeControllersConfigurationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in KubeControllersConfigurationStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.KubeControllersConfigurationStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LicenseKey) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.LicenseKey"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LicenseKeyList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.LicenseKeyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LicenseKeySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.LicenseKeySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LicenseKeyStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.LicenseKeyStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.LoadBalancerControllerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ManagedCluster) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ManagedCluster"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ManagedClusterList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ManagedClusterList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ManagedClusterSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ManagedClusterSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ManagedClusterStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ManagedClusterStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ManagedClusterStatusCondition) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ManagedClusterStatusCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MigrationControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.MigrationControllerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamedSelector) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NamedSelector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamesAndLabelsMatch) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NamesAndLabelsMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamespaceControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NamespaceControllerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicy) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkSet) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NetworkSet"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkSetList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NetworkSetList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkSetSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NetworkSetSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.NodeControllerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PacketCapture) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PacketCapture"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PacketCaptureFile) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PacketCaptureFile"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PacketCaptureList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PacketCaptureList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PacketCaptureRule) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PacketCaptureRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PacketCaptureSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PacketCaptureSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PacketCaptureStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PacketCaptureStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyControllerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyRecommendationScope) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyRecommendationScope"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyRecommendationScopeHostEndpointSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyRecommendationScopeHostEndpointSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyRecommendationScopeList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyRecommendationScopeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyRecommendationScopeNamespaceSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyRecommendationScopeNamespaceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyRecommendationScopeSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyRecommendationScopeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyRecommendationScopeStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyRecommendationScopeStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyRecommendationScopeStatusCondition) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PolicyRecommendationScopeStatusCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Position) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.Position"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PrefixAdvertisement) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.PrefixAdvertisement"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Profile) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.Profile"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProfileList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ProfileList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProfileSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ProfileSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProtoPort) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ProtoPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Pull) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.Pull"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RemoteClusterConfiguration) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.RemoteClusterConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RemoteClusterConfigurationList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.RemoteClusterConfigurationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RemoteClusterConfigurationSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.RemoteClusterConfigurationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RemoteClusterSyncOptions) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.RemoteClusterSyncOptions"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReportData) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ReportData"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReportJob) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ReportJob"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReportSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ReportSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReportStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ReportStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReportTemplate) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ReportTemplate"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReportTypeSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ReportTypeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ResourceID) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ResourceID"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteTableIDRange) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.RouteTableIDRange"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteTableRange) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.RouteTableRange"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Rule) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.Rule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RuleMetadata) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.RuleMetadata"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecurityEventWebhook) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.SecurityEventWebhook"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecurityEventWebhookConfigVar) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.SecurityEventWebhookConfigVar"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecurityEventWebhookConfigVarSource) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.SecurityEventWebhookConfigVarSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecurityEventWebhookList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.SecurityEventWebhookList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecurityEventWebhookSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.SecurityEventWebhookSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceAccountControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ServiceAccountControllerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceAccountMatch) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ServiceAccountMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceClusterIPBlock) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ServiceClusterIPBlock"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceExternalIPBlock) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ServiceExternalIPBlock"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceLoadBalancerIPBlock) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ServiceLoadBalancerIPBlock"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceMatch) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ServiceMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedGlobalNetworkPolicy) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedGlobalNetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedGlobalNetworkPolicyList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedGlobalNetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedGlobalNetworkPolicySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedGlobalNetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedKubernetesNetworkPolicy) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedKubernetesNetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedKubernetesNetworkPolicyList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedKubernetesNetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedKubernetesNetworkPolicySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedKubernetesNetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedNetworkPolicy) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedNetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedNetworkPolicyList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedNetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StagedNetworkPolicySpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.StagedNetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Template) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.Template"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ThreatFeedFormat) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ThreatFeedFormat"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ThreatFeedFormatCSV) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ThreatFeedFormatCSV"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ThreatFeedFormatJSON) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ThreatFeedFormatJSON"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ThreatFeedFormatNewlineDelimited) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.ThreatFeedFormatNewlineDelimited"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Tier) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.Tier"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TierList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.TierList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TierSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.TierSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TierStatus) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.TierStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UIDashboard) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UIDashboard"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UIGraphLayer) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UIGraphLayer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UIGraphNode) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UIGraphNode"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UIGraphNodeView) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UIGraphNodeView"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UIGraphView) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UIGraphView"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UISettings) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UISettings"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UISettingsGroup) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UISettingsGroup"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UISettingsGroupList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UISettingsGroupList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UISettingsGroupSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UISettingsGroupSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UISettingsList) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UISettingsList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UISettingsSpec) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.UISettingsSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadEndpointControllerConfig) OpenAPIModelName() string {
	return "com.github.tigera.api.pkg.apis.projectcalico.v3.WorkloadEndpointControllerConfig"
}
