// Copyright (c) 2019 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package projectcalico

// GlobalReportTypeListerExpansion allows custom methods to be added to
// GlobalReportTypeLister.
type GlobalReportTypeListerExpansion interface{}

// GlobalReportTypeNamespaceListerExpansion allows custom methods to be added to
// GlobalReportTypeNamespaceLister.
type GlobalReportTypeNamespaceListerExpansion interface{}
