// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package projectcalico

import (
	projectcalico "github.com/tigera/api/pkg/apis/projectcalico"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GlobalAlertTemplateLister helps list GlobalAlertTemplates.
// All objects returned here must be treated as read-only.
type GlobalAlertTemplateLister interface {
	// List lists all GlobalAlertTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalico.GlobalAlertTemplate, err error)
	// Get retrieves the GlobalAlertTemplate from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*projectcalico.GlobalAlertTemplate, error)
	GlobalAlertTemplateListerExpansion
}

// globalAlertTemplateLister implements the GlobalAlertTemplateLister interface.
type globalAlertTemplateLister struct {
	indexer cache.Indexer
}

// NewGlobalAlertTemplateLister returns a new GlobalAlertTemplateLister.
func NewGlobalAlertTemplateLister(indexer cache.Indexer) GlobalAlertTemplateLister {
	return &globalAlertTemplateLister{indexer: indexer}
}

// List lists all GlobalAlertTemplates in the indexer.
func (s *globalAlertTemplateLister) List(selector labels.Selector) (ret []*projectcalico.GlobalAlertTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*projectcalico.GlobalAlertTemplate))
	})
	return ret, err
}

// Get retrieves the GlobalAlertTemplate from the index for a given name.
func (s *globalAlertTemplateLister) Get(name string) (*projectcalico.GlobalAlertTemplate, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(projectcalico.Resource("globalalerttemplate"), name)
	}
	return obj.(*projectcalico.GlobalAlertTemplate), nil
}
