// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package projectcalico

import (
	projectcalico "github.com/tigera/api/pkg/apis/projectcalico"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LicenseKeyLister helps list LicenseKeys.
// All objects returned here must be treated as read-only.
type LicenseKeyLister interface {
	// List lists all LicenseKeys in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalico.LicenseKey, err error)
	// Get retrieves the LicenseKey from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*projectcalico.LicenseKey, error)
	LicenseKeyListerExpansion
}

// licenseKeyLister implements the LicenseKeyLister interface.
type licenseKeyLister struct {
	indexer cache.Indexer
}

// NewLicenseKeyLister returns a new LicenseKeyLister.
func NewLicenseKeyLister(indexer cache.Indexer) LicenseKeyLister {
	return &licenseKeyLister{indexer: indexer}
}

// List lists all LicenseKeys in the indexer.
func (s *licenseKeyLister) List(selector labels.Selector) (ret []*projectcalico.LicenseKey, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*projectcalico.LicenseKey))
	})
	return ret, err
}

// Get retrieves the LicenseKey from the index for a given name.
func (s *licenseKeyLister) Get(name string) (*projectcalico.LicenseKey, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(projectcalico.Resource("licensekey"), name)
	}
	return obj.(*projectcalico.LicenseKey), nil
}
