// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ApplicationLayerControllerConfigApplyConfiguration represents a declarative configuration of the ApplicationLayerControllerConfig type for use
// with apply.
//
// ApplicationLayerControllerConfig configures the application-layer controller-group.
type ApplicationLayerControllerConfigApplyConfiguration struct {
	// ReconcilerPeriod is the period to perform reconciliation. [Default: 30s]
	ReconcilerPeriod *v1.Duration `json:"reconcilerPeriod,omitempty"`
}

// ApplicationLayerControllerConfigApplyConfiguration constructs a declarative configuration of the ApplicationLayerControllerConfig type for use with
// apply.
func ApplicationLayerControllerConfig() *ApplicationLayerControllerConfigApplyConfiguration {
	return &ApplicationLayerControllerConfigApplyConfiguration{}
}

// WithReconcilerPeriod sets the ReconcilerPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReconcilerPeriod field is set to the value of the last call.
func (b *ApplicationLayerControllerConfigApplyConfiguration) WithReconcilerPeriod(value v1.Duration) *ApplicationLayerControllerConfigApplyConfiguration {
	b.ReconcilerPeriod = &value
	return b
}
