// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// AuthorizationReviewResourceAttributesApplyConfiguration represents a declarative configuration of the AuthorizationReviewResourceAttributes type for use
// with apply.
type AuthorizationReviewResourceAttributesApplyConfiguration struct {
	// The API Group to check.
	APIGroup *string `json:"apiGroup,omitempty"`
	// The set of resources to check within the same API Group.
	Resources []string `json:"resources,omitempty"`
	// The set of verbs to check. This is expanded for each resource and within the same API Group.
	Verbs []string `json:"verbs,omitempty"`
}

// AuthorizationReviewResourceAttributesApplyConfiguration constructs a declarative configuration of the AuthorizationReviewResourceAttributes type for use with
// apply.
func AuthorizationReviewResourceAttributes() *AuthorizationReviewResourceAttributesApplyConfiguration {
	return &AuthorizationReviewResourceAttributesApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *AuthorizationReviewResourceAttributesApplyConfiguration) WithAPIGroup(value string) *AuthorizationReviewResourceAttributesApplyConfiguration {
	b.APIGroup = &value
	return b
}

// WithResources adds the given value to the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resources field.
func (b *AuthorizationReviewResourceAttributesApplyConfiguration) WithResources(values ...string) *AuthorizationReviewResourceAttributesApplyConfiguration {
	for i := range values {
		b.Resources = append(b.Resources, values[i])
	}
	return b
}

// WithVerbs adds the given value to the Verbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verbs field.
func (b *AuthorizationReviewResourceAttributesApplyConfiguration) WithVerbs(values ...string) *AuthorizationReviewResourceAttributesApplyConfiguration {
	for i := range values {
		b.Verbs = append(b.Verbs, values[i])
	}
	return b
}
