// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// AuthorizedResourceGroupApplyConfiguration represents a declarative configuration of the AuthorizedResourceGroup type for use
// with apply.
type AuthorizedResourceGroupApplyConfiguration struct {
	// The tier.  This is only valid for tiered policies, and tiers.
	Tier *string `json:"tier,omitempty"`
	// The namespace. If this is empty then the user is authorized cluster-wide (i.e. across all namespaces). This will
	// always be empty for cluster-scoped resources when the user is authorized.
	Namespace *string `json:"namespace,omitempty"`
	// The UISettingsGroup name. This is only valid for uisettingsgroup/data sub resources.
	UISettingsGroup *string `json:"uiSettingsGroup,omitempty"`
	// ManagedCluster is the name of the ManagedCluster. This is only valid for managedclusters.
	ManagedCluster *string `json:"managedCluster,omitempty"`
}

// AuthorizedResourceGroupApplyConfiguration constructs a declarative configuration of the AuthorizedResourceGroup type for use with
// apply.
func AuthorizedResourceGroup() *AuthorizedResourceGroupApplyConfiguration {
	return &AuthorizedResourceGroupApplyConfiguration{}
}

// WithTier sets the Tier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tier field is set to the value of the last call.
func (b *AuthorizedResourceGroupApplyConfiguration) WithTier(value string) *AuthorizedResourceGroupApplyConfiguration {
	b.Tier = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *AuthorizedResourceGroupApplyConfiguration) WithNamespace(value string) *AuthorizedResourceGroupApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithUISettingsGroup sets the UISettingsGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UISettingsGroup field is set to the value of the last call.
func (b *AuthorizedResourceGroupApplyConfiguration) WithUISettingsGroup(value string) *AuthorizedResourceGroupApplyConfiguration {
	b.UISettingsGroup = &value
	return b
}

// WithManagedCluster sets the ManagedCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagedCluster field is set to the value of the last call.
func (b *AuthorizedResourceGroupApplyConfiguration) WithManagedCluster(value string) *AuthorizedResourceGroupApplyConfiguration {
	b.ManagedCluster = &value
	return b
}
