// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// AuthorizedResourceVerbApplyConfiguration represents a declarative configuration of the AuthorizedResourceVerb type for use
// with apply.
type AuthorizedResourceVerbApplyConfiguration struct {
	// The verb.
	Verb *string `json:"verb,omitempty"`
	// The group of resource instances that are authorized for this verb.
	ResourceGroups []AuthorizedResourceGroupApplyConfiguration `json:"resourceGroups,omitempty"`
}

// AuthorizedResourceVerbApplyConfiguration constructs a declarative configuration of the AuthorizedResourceVerb type for use with
// apply.
func AuthorizedResourceVerb() *AuthorizedResourceVerbApplyConfiguration {
	return &AuthorizedResourceVerbApplyConfiguration{}
}

// WithVerb sets the Verb field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Verb field is set to the value of the last call.
func (b *AuthorizedResourceVerbApplyConfiguration) WithVerb(value string) *AuthorizedResourceVerbApplyConfiguration {
	b.Verb = &value
	return b
}

// WithResourceGroups adds the given value to the ResourceGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceGroups field.
func (b *AuthorizedResourceVerbApplyConfiguration) WithResourceGroups(values ...*AuthorizedResourceGroupApplyConfiguration) *AuthorizedResourceVerbApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceGroups")
		}
		b.ResourceGroups = append(b.ResourceGroups, *values[i])
	}
	return b
}
