// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// AuthorizedResourceVerbsApplyConfiguration represents a declarative configuration of the AuthorizedResourceVerbs type for use
// with apply.
type AuthorizedResourceVerbsApplyConfiguration struct {
	// The API group.
	APIGroup *string `json:"apiGroup,omitempty"`
	// The resource.
	Resource *string `json:"resource,omitempty"`
	// The set of authorized actions for this resource. For a specific verb, this contains the set of resources for
	// which the user is authorized to perform that action. This is calculated to avoid duplication such that a single
	// resource instance can only be associated with a single entry in this slice. This allows a consumer of this API
	// to issue a minimal set of queries (e.g. watches) that cover, uniquely, the authorized set of resources.
	Verbs []AuthorizedResourceVerbApplyConfiguration `json:"verbs,omitempty"`
}

// AuthorizedResourceVerbsApplyConfiguration constructs a declarative configuration of the AuthorizedResourceVerbs type for use with
// apply.
func AuthorizedResourceVerbs() *AuthorizedResourceVerbsApplyConfiguration {
	return &AuthorizedResourceVerbsApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *AuthorizedResourceVerbsApplyConfiguration) WithAPIGroup(value string) *AuthorizedResourceVerbsApplyConfiguration {
	b.APIGroup = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *AuthorizedResourceVerbsApplyConfiguration) WithResource(value string) *AuthorizedResourceVerbsApplyConfiguration {
	b.Resource = &value
	return b
}

// WithVerbs adds the given value to the Verbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verbs field.
func (b *AuthorizedResourceVerbsApplyConfiguration) WithVerbs(values ...*AuthorizedResourceVerbApplyConfiguration) *AuthorizedResourceVerbsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVerbs")
		}
		b.Verbs = append(b.Verbs, *values[i])
	}
	return b
}
