// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// AuthorizationReviewSpecApplyConfiguration represents a declarative configuration of the AuthorizationReviewSpec type for use
// with apply.
type AuthorizationReviewSpecApplyConfiguration struct {
	// The set of resource attributes that are being checked. Each resource attribute is expanded into individual
	// kind/resource and verbs.
	ResourceAttributes []AuthorizationReviewResourceAttributesApplyConfiguration `json:"resourceAttributes,omitempty"`
	// User is the user you're testing for.
	// If you specify "User" but not "Groups", then is it interpreted as "What if User were not a member of any groups"
	User *string `json:"user,omitempty"`
	// Groups is the groups you're testing for.
	Groups []string `json:"groups,omitempty"`
	// Extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer
	// it needs a reflection here.
	Extra map[string][]string `json:"extra,omitempty"`
	// UID information about the requesting user.
	UID *string `json:"uid,omitempty"`
}

// AuthorizationReviewSpecApplyConfiguration constructs a declarative configuration of the AuthorizationReviewSpec type for use with
// apply.
func AuthorizationReviewSpec() *AuthorizationReviewSpecApplyConfiguration {
	return &AuthorizationReviewSpecApplyConfiguration{}
}

// WithResourceAttributes adds the given value to the ResourceAttributes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceAttributes field.
func (b *AuthorizationReviewSpecApplyConfiguration) WithResourceAttributes(values ...*AuthorizationReviewResourceAttributesApplyConfiguration) *AuthorizationReviewSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceAttributes")
		}
		b.ResourceAttributes = append(b.ResourceAttributes, *values[i])
	}
	return b
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *AuthorizationReviewSpecApplyConfiguration) WithUser(value string) *AuthorizationReviewSpecApplyConfiguration {
	b.User = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *AuthorizationReviewSpecApplyConfiguration) WithGroups(values ...string) *AuthorizationReviewSpecApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithExtra puts the entries into the Extra field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Extra field,
// overwriting an existing map entries in Extra field with the same key.
func (b *AuthorizationReviewSpecApplyConfiguration) WithExtra(entries map[string][]string) *AuthorizationReviewSpecApplyConfiguration {
	if b.Extra == nil && len(entries) > 0 {
		b.Extra = make(map[string][]string, len(entries))
	}
	for k, v := range entries {
		b.Extra[k] = v
	}
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *AuthorizationReviewSpecApplyConfiguration) WithUID(value string) *AuthorizationReviewSpecApplyConfiguration {
	b.UID = &value
	return b
}
