// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// AuthorizationReviewStatusApplyConfiguration represents a declarative configuration of the AuthorizationReviewStatus type for use
// with apply.
type AuthorizationReviewStatusApplyConfiguration struct {
	// The set of authorized resource actions. A given API Group and resource combination will appear at most once in
	// this slice.
	AuthorizedResourceVerbs []AuthorizedResourceVerbsApplyConfiguration `json:"authorizedResourceVerbs,omitempty"`
}

// AuthorizationReviewStatusApplyConfiguration constructs a declarative configuration of the AuthorizationReviewStatus type for use with
// apply.
func AuthorizationReviewStatus() *AuthorizationReviewStatusApplyConfiguration {
	return &AuthorizationReviewStatusApplyConfiguration{}
}

// WithAuthorizedResourceVerbs adds the given value to the AuthorizedResourceVerbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthorizedResourceVerbs field.
func (b *AuthorizationReviewStatusApplyConfiguration) WithAuthorizedResourceVerbs(values ...*AuthorizedResourceVerbsApplyConfiguration) *AuthorizationReviewStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAuthorizedResourceVerbs")
		}
		b.AuthorizedResourceVerbs = append(b.AuthorizedResourceVerbs, *values[i])
	}
	return b
}
