// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BFDInterfaceApplyConfiguration represents a declarative configuration of the BFDInterface type for use
// with apply.
//
// BFDInterface contains per-interface parameters for BFD failure detection.
type BFDInterfaceApplyConfiguration struct {
	// MatchPattern is a pattern to match one or more interfaces.
	// Supports exact interface names, match on interface prefixes (e.g., “eth*”),
	// or “*” to select all interfaces on the selected node(s).
	MatchPattern *string `json:"matchPattern,omitempty"`
	// MinimumRecvInterval is the minimum interval between received BFD packets. Must be a whole number of milliseconds greater than 0.
	MinimumRecvInterval *v1.Duration `json:"minimumRecvInterval,omitempty"`
	// MinimumSendInterval is the minimum interval between transmitted BFD packets. Must be a whole number of milliseconds greater than 0.
	MinimumSendInterval *v1.Duration `json:"minimumSendInterval,omitempty"`
	// IdleSendInterval is the interval between transmitted BFD packets when the BFD peer is idle. Must be a whole number of milliseconds greater than 0.
	IdleSendInterval *v1.Duration `json:"idleSendInterval,omitempty"`
	// Multiplier is the number of intervals that must pass without receiving a BFD packet before the peer is considered down.
	Multiplier *int `json:"multiplier,omitempty"`
}

// BFDInterfaceApplyConfiguration constructs a declarative configuration of the BFDInterface type for use with
// apply.
func BFDInterface() *BFDInterfaceApplyConfiguration {
	return &BFDInterfaceApplyConfiguration{}
}

// WithMatchPattern sets the MatchPattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchPattern field is set to the value of the last call.
func (b *BFDInterfaceApplyConfiguration) WithMatchPattern(value string) *BFDInterfaceApplyConfiguration {
	b.MatchPattern = &value
	return b
}

// WithMinimumRecvInterval sets the MinimumRecvInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumRecvInterval field is set to the value of the last call.
func (b *BFDInterfaceApplyConfiguration) WithMinimumRecvInterval(value v1.Duration) *BFDInterfaceApplyConfiguration {
	b.MinimumRecvInterval = &value
	return b
}

// WithMinimumSendInterval sets the MinimumSendInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumSendInterval field is set to the value of the last call.
func (b *BFDInterfaceApplyConfiguration) WithMinimumSendInterval(value v1.Duration) *BFDInterfaceApplyConfiguration {
	b.MinimumSendInterval = &value
	return b
}

// WithIdleSendInterval sets the IdleSendInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdleSendInterval field is set to the value of the last call.
func (b *BFDInterfaceApplyConfiguration) WithIdleSendInterval(value v1.Duration) *BFDInterfaceApplyConfiguration {
	b.IdleSendInterval = &value
	return b
}

// WithMultiplier sets the Multiplier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Multiplier field is set to the value of the last call.
func (b *BFDInterfaceApplyConfiguration) WithMultiplier(value int) *BFDInterfaceApplyConfiguration {
	b.Multiplier = &value
	return b
}
