// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// DeepPacketInspectionSpecApplyConfiguration represents a declarative configuration of the DeepPacketInspectionSpec type for use
// with apply.
//
// DeepPacketInspectionSpec contains the values of the deep packet inspection.
type DeepPacketInspectionSpecApplyConfiguration struct {
	// The selector is an expression used to pick out the endpoints for which deep packet inspection should
	// be performed on. The selector will only match endpoints in the same namespace as the
	// DeepPacketInspection resource.
	//
	// Selector expressions follow this syntax:
	//
	// label == "string_literal"  ->  comparison, e.g. my_label == "foo bar"
	// label != "string_literal"   ->  not equal; also matches if label is not present
	// label in { "a", "b", "c", ... }  ->  true if the value of label X is one of "a", "b", "c"
	// label not in { "a", "b", "c", ... }  ->  true if the value of label X is not one of "a", "b", "c"
	// has(label_name)  -> True if that label is present
	// ! expr -> negation of expr
	// expr && expr  -> Short-circuit and
	// expr || expr  -> Short-circuit or
	// ( expr ) -> parens for grouping
	// all() or the empty selector -> matches all endpoints.
	//
	// Label names are allowed to contain alphanumerics, -, _ and /. String literals are more permissive
	// but they do not support escape characters.
	//
	// Examples (with made-up labels):
	//
	// type == "webserver" && deployment == "prod"
	// type in {"frontend", "backend"}
	// deployment != "dev"
	// ! has(label_name)
	Selector *string `json:"selector,omitempty"`
}

// DeepPacketInspectionSpecApplyConfiguration constructs a declarative configuration of the DeepPacketInspectionSpec type for use with
// apply.
func DeepPacketInspectionSpec() *DeepPacketInspectionSpecApplyConfiguration {
	return &DeepPacketInspectionSpecApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *DeepPacketInspectionSpecApplyConfiguration) WithSelector(value string) *DeepPacketInspectionSpecApplyConfiguration {
	b.Selector = &value
	return b
}
