// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
)

// EgressGatewayRuleApplyConfiguration represents a declarative configuration of the EgressGatewayRule type for use
// with apply.
//
// EgressGatewayRule defines an Egress Gateway to reach a destination network
type EgressGatewayRuleApplyConfiguration struct {
	// The destination network that can be reached via egress gateway.
	// If no destination is set, the default route, 0.0.0.0/0, is used instead.
	Destination *EgressGatewayPolicyDestinationSpecApplyConfiguration `json:"destination,omitempty"`
	// The description of the EgressGatewayPolicy rule.
	Description *string `json:"description,omitempty"`
	// Gateway specifies the egress gateway that should be used for the specified destination.
	// If no gateway is set then the destination is routed normally rather than via an egress gateway.
	Gateway *EgressSpecApplyConfiguration `json:"gateway,omitempty"`
	// GatewayPreference specifies which egress gateways to use. If set to PreferNodeLocal, egress gateways in the same node as
	// the client will be used if available. Otherwise all the active egress gateways will be used.
	GatewayPreference *projectcalicov3.GatewayPreferenceType `json:"gatewayPreference,omitempty"`
}

// EgressGatewayRuleApplyConfiguration constructs a declarative configuration of the EgressGatewayRule type for use with
// apply.
func EgressGatewayRule() *EgressGatewayRuleApplyConfiguration {
	return &EgressGatewayRuleApplyConfiguration{}
}

// WithDestination sets the Destination field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Destination field is set to the value of the last call.
func (b *EgressGatewayRuleApplyConfiguration) WithDestination(value *EgressGatewayPolicyDestinationSpecApplyConfiguration) *EgressGatewayRuleApplyConfiguration {
	b.Destination = value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *EgressGatewayRuleApplyConfiguration) WithDescription(value string) *EgressGatewayRuleApplyConfiguration {
	b.Description = &value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *EgressGatewayRuleApplyConfiguration) WithGateway(value *EgressSpecApplyConfiguration) *EgressGatewayRuleApplyConfiguration {
	b.Gateway = value
	return b
}

// WithGatewayPreference sets the GatewayPreference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GatewayPreference field is set to the value of the last call.
func (b *EgressGatewayRuleApplyConfiguration) WithGatewayPreference(value projectcalicov3.GatewayPreferenceType) *EgressGatewayRuleApplyConfiguration {
	b.GatewayPreference = &value
	return b
}
