// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// EgressGatewaySpecApplyConfiguration represents a declarative configuration of the EgressGatewaySpec type for use
// with apply.
//
// EgressGatewaySpec allows to define an egress gateway directly, or to refer to
// an egress gateway policy resource.
type EgressGatewaySpecApplyConfiguration struct {
	// Only one of these may be set.
	// Reference to an EgressGatewayPolicy to use.
	Policy *string `json:"policy,omitempty"`
	// Reference to a specific EgressGateway to use.
	Gateway *EgressSpecApplyConfiguration `json:"gateway,omitempty"`
}

// EgressGatewaySpecApplyConfiguration constructs a declarative configuration of the EgressGatewaySpec type for use with
// apply.
func EgressGatewaySpec() *EgressGatewaySpecApplyConfiguration {
	return &EgressGatewaySpecApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *EgressGatewaySpecApplyConfiguration) WithPolicy(value string) *EgressGatewaySpecApplyConfiguration {
	b.Policy = &value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *EgressGatewaySpecApplyConfiguration) WithGateway(value *EgressSpecApplyConfiguration) *EgressGatewaySpecApplyConfiguration {
	b.Gateway = value
	return b
}
