// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// EgressGatewayPolicyDestinationSpecApplyConfiguration represents a declarative configuration of the EgressGatewayPolicyDestinationSpec type for use
// with apply.
//
// DestinationSpec define a destination network that can be reached via an egress gateway
type EgressGatewayPolicyDestinationSpecApplyConfiguration struct {
	// The destination network CIDR.
	CIDR *string `json:"cidr,omitempty"`
}

// EgressGatewayPolicyDestinationSpecApplyConfiguration constructs a declarative configuration of the EgressGatewayPolicyDestinationSpec type for use with
// apply.
func EgressGatewayPolicyDestinationSpec() *EgressGatewayPolicyDestinationSpecApplyConfiguration {
	return &EgressGatewayPolicyDestinationSpecApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *EgressGatewayPolicyDestinationSpecApplyConfiguration) WithCIDR(value string) *EgressGatewayPolicyDestinationSpecApplyConfiguration {
	b.CIDR = &value
	return b
}
