// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GlobalThreatFeedStatusApplyConfiguration represents a declarative configuration of the GlobalThreatFeedStatus type for use
// with apply.
type GlobalThreatFeedStatusApplyConfiguration struct {
	LastSuccessfulSync   *v1.Time                           `json:"lastSuccessfulSync,omitempty"`
	LastSuccessfulSearch *v1.Time                           `json:"lastSuccessfulSearch,omitempty"`
	ErrorConditions      []ErrorConditionApplyConfiguration `json:"errorConditions,omitempty"`
}

// GlobalThreatFeedStatusApplyConfiguration constructs a declarative configuration of the GlobalThreatFeedStatus type for use with
// apply.
func GlobalThreatFeedStatus() *GlobalThreatFeedStatusApplyConfiguration {
	return &GlobalThreatFeedStatusApplyConfiguration{}
}

// WithLastSuccessfulSync sets the LastSuccessfulSync field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulSync field is set to the value of the last call.
func (b *GlobalThreatFeedStatusApplyConfiguration) WithLastSuccessfulSync(value v1.Time) *GlobalThreatFeedStatusApplyConfiguration {
	b.LastSuccessfulSync = &value
	return b
}

// WithLastSuccessfulSearch sets the LastSuccessfulSearch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulSearch field is set to the value of the last call.
func (b *GlobalThreatFeedStatusApplyConfiguration) WithLastSuccessfulSearch(value v1.Time) *GlobalThreatFeedStatusApplyConfiguration {
	b.LastSuccessfulSearch = &value
	return b
}

// WithErrorConditions adds the given value to the ErrorConditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ErrorConditions field.
func (b *GlobalThreatFeedStatusApplyConfiguration) WithErrorConditions(values ...*ErrorConditionApplyConfiguration) *GlobalThreatFeedStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithErrorConditions")
		}
		b.ErrorConditions = append(b.ErrorConditions, *values[i])
	}
	return b
}
