// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GlobalAlertSpecApplyConfiguration represents a declarative configuration of the GlobalAlertSpec type for use
// with apply.
type GlobalAlertSpecApplyConfiguration struct {
	// Type will dictate how the fields of the GlobalAlert will be utilized.
	// Each Type will have different usages and defaults for the fields. [Default: RuleBased]
	Type *projectcalicov3.GlobalAlertType `json:"type,omitempty"`
	// Template for the description field in generated events, description is used if this is omitted.
	Summary *string `json:"summary,omitempty"`
	// Human-readable description of the template.
	Description *string `json:"description,omitempty"`
	// Severity of the alert for display in Manager.
	Severity *int `json:"severity,omitempty"`
	// If Type is RuleBased, it is how often the query defined will run.
	// If Type is AnomalyDetection it is how often the detector will be run.
	Period *v1.Duration `json:"period,omitempty"`
	// How much data to gather at once.
	// If Type is RuleBased, it must exceed audit log flush interval, dnsLogsFlushInterval, or flowLogsFlushInterval as appropriate.
	Lookback *v1.Duration `json:"lookback,omitempty"`
	// DataSet determines which dataset type the Query will use.
	// Required and used only if Type is RuleBased.
	DataSet *string `json:"dataSet,omitempty"`
	// Which data to include from the source data set. Written in a domain-specific query language. Only used if Type is RuleBased.
	Query *string `json:"query,omitempty"`
	// An optional list of fields to aggregate results.
	// Only used if Type is RuleBased.
	AggregateBy []string `json:"aggregateBy,omitempty"`
	// Which field to aggregate results by if using a metric other than count.
	// Only used if Type is RuleBased.
	Field *string `json:"field,omitempty"`
	// A metric to apply to aggregated results. count is the number of log entries matching the aggregation pattern.
	// Others are applied only to numeric fields in the logs.
	// Only used if Type is RuleBased.
	Metric *string `json:"metric,omitempty"`
	// Compare the value of the metric to the threshold using this condition.
	// Only used if Type is RuleBased.
	Condition *string `json:"condition,omitempty"`
	// A numeric value to compare the value of the metric against.
	// Only used if Type is RuleBased.
	Threshold *float64 `json:"threshold,omitempty"`
	// An optional list of values to replace variable names in query.
	// Only used if Type is RuleBased.
	Substitutions []GlobalAlertSubstitutionApplyConfiguration `json:"substitutions,omitempty"`
	// Parameters for configuring an AnomalyDetection run.
	// Only used if Type is AnomalyDetection.
	Detector *DetectorParamsApplyConfiguration `json:"detector,omitempty"`
}

// GlobalAlertSpecApplyConfiguration constructs a declarative configuration of the GlobalAlertSpec type for use with
// apply.
func GlobalAlertSpec() *GlobalAlertSpecApplyConfiguration {
	return &GlobalAlertSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithType(value projectcalicov3.GlobalAlertType) *GlobalAlertSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithSummary sets the Summary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Summary field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithSummary(value string) *GlobalAlertSpecApplyConfiguration {
	b.Summary = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithDescription(value string) *GlobalAlertSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithSeverity sets the Severity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Severity field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithSeverity(value int) *GlobalAlertSpecApplyConfiguration {
	b.Severity = &value
	return b
}

// WithPeriod sets the Period field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Period field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithPeriod(value v1.Duration) *GlobalAlertSpecApplyConfiguration {
	b.Period = &value
	return b
}

// WithLookback sets the Lookback field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lookback field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithLookback(value v1.Duration) *GlobalAlertSpecApplyConfiguration {
	b.Lookback = &value
	return b
}

// WithDataSet sets the DataSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataSet field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithDataSet(value string) *GlobalAlertSpecApplyConfiguration {
	b.DataSet = &value
	return b
}

// WithQuery sets the Query field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Query field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithQuery(value string) *GlobalAlertSpecApplyConfiguration {
	b.Query = &value
	return b
}

// WithAggregateBy adds the given value to the AggregateBy field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AggregateBy field.
func (b *GlobalAlertSpecApplyConfiguration) WithAggregateBy(values ...string) *GlobalAlertSpecApplyConfiguration {
	for i := range values {
		b.AggregateBy = append(b.AggregateBy, values[i])
	}
	return b
}

// WithField sets the Field field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Field field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithField(value string) *GlobalAlertSpecApplyConfiguration {
	b.Field = &value
	return b
}

// WithMetric sets the Metric field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metric field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithMetric(value string) *GlobalAlertSpecApplyConfiguration {
	b.Metric = &value
	return b
}

// WithCondition sets the Condition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Condition field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithCondition(value string) *GlobalAlertSpecApplyConfiguration {
	b.Condition = &value
	return b
}

// WithThreshold sets the Threshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Threshold field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithThreshold(value float64) *GlobalAlertSpecApplyConfiguration {
	b.Threshold = &value
	return b
}

// WithSubstitutions adds the given value to the Substitutions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Substitutions field.
func (b *GlobalAlertSpecApplyConfiguration) WithSubstitutions(values ...*GlobalAlertSubstitutionApplyConfiguration) *GlobalAlertSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSubstitutions")
		}
		b.Substitutions = append(b.Substitutions, *values[i])
	}
	return b
}

// WithDetector sets the Detector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Detector field is set to the value of the last call.
func (b *GlobalAlertSpecApplyConfiguration) WithDetector(value *DetectorParamsApplyConfiguration) *GlobalAlertSpecApplyConfiguration {
	b.Detector = value
	return b
}
