// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// L2BridgeSpecApplyConfiguration represents a declarative configuration of the L2BridgeSpec type for use
// with apply.
//
// L2BridgeSpec configures a Layer 2 bridged network.  Workload interfaces
// are attached to a Linux bridge on each node as 802.1Q access ports; the
// bridge connects to the physical network via a single trunk port defined
// in HostConfig.  (HostConnections is currently capped at one entry per
// HostConfig; multiple trunk ports per host is a future extension.)
//
// Calico-managed bridges run in tagged-only mode: the bridge has
// vlan_filtering=1 and vlan_default_pvid=0, so untagged frames are dropped
// on the wire by default.  Operators that need untagged-on-wire delivery
// for a trunk opt in by setting L2HostTrunkPort.NativeVLAN to the VLAN ID
// that should be carried untagged on that trunk.
type L2BridgeSpecApplyConfiguration struct {
	// VLANs is the authoritative list of 802.1Q VLAN segments carried by
	// this network.  Each entry defines a single VLAN ID or a contiguous
	// range of VLAN IDs, plus the subnets associated with that segment.
	//
	// The set of VLAN IDs the network may carry is the union of all IDs and
	// ranges in this list.  Entries are not required to be disjoint: if the
	// same VLAN ID appears in more than one entry the network still simply
	// carries that VLAN, so overlap is permitted and not validated here.
	//
	// Workload attachments select a single entry via the CNI config
	// "vlan" field; if spec.vlans has exactly one entry that resolves to
	// a single VLAN ID, the CNI config "vlan" field may be omitted.
	VLANs []L2VLANSpecApplyConfiguration `json:"vlans,omitempty"`
	// HostConfig defines per-node-group configuration for this network.
	// When multiple entries are present, the first entry whose
	// nodeSelector matches a given node is used; all other entries are
	// ignored for that node.  Entries with no nodeSelector match all
	// nodes.
	HostConfig []L2HostConfigApplyConfiguration `json:"hostConfig,omitempty"`
}

// L2BridgeSpecApplyConfiguration constructs a declarative configuration of the L2BridgeSpec type for use with
// apply.
func L2BridgeSpec() *L2BridgeSpecApplyConfiguration {
	return &L2BridgeSpecApplyConfiguration{}
}

// WithVLANs adds the given value to the VLANs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VLANs field.
func (b *L2BridgeSpecApplyConfiguration) WithVLANs(values ...*L2VLANSpecApplyConfiguration) *L2BridgeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVLANs")
		}
		b.VLANs = append(b.VLANs, *values[i])
	}
	return b
}

// WithHostConfig adds the given value to the HostConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HostConfig field.
func (b *L2BridgeSpecApplyConfiguration) WithHostConfig(values ...*L2HostConfigApplyConfiguration) *L2BridgeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHostConfig")
		}
		b.HostConfig = append(b.HostConfig, *values[i])
	}
	return b
}
