// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// L2ExistingBridgeApplyConfiguration represents a declarative configuration of the L2ExistingBridge type for use
// with apply.
//
// L2ExistingBridge configures attachment to a pre-existing bridge device.
type L2ExistingBridgeApplyConfiguration struct {
	// Name is the Linux bridge device name (e.g. "br0").
	Name *string `json:"name,omitempty"`
}

// L2ExistingBridgeApplyConfiguration constructs a declarative configuration of the L2ExistingBridge type for use with
// apply.
func L2ExistingBridge() *L2ExistingBridgeApplyConfiguration {
	return &L2ExistingBridgeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *L2ExistingBridgeApplyConfiguration) WithName(value string) *L2ExistingBridgeApplyConfiguration {
	b.Name = &value
	return b
}
