// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// L2HostConnectionApplyConfiguration represents a declarative configuration of the L2HostConnection type for use
// with apply.
//
// L2HostConnection defines a single host-side connection to the bridge.
// Exactly one connection type must be set.
type L2HostConnectionApplyConfiguration struct {
	// TrunkPort enslaves a host interface to the bridge as an 802.1Q
	// trunk.
	TrunkPort *L2HostTrunkPortApplyConfiguration `json:"trunkPort,omitempty"`
}

// L2HostConnectionApplyConfiguration constructs a declarative configuration of the L2HostConnection type for use with
// apply.
func L2HostConnection() *L2HostConnectionApplyConfiguration {
	return &L2HostConnectionApplyConfiguration{}
}

// WithTrunkPort sets the TrunkPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrunkPort field is set to the value of the last call.
func (b *L2HostConnectionApplyConfiguration) WithTrunkPort(value *L2HostTrunkPortApplyConfiguration) *L2HostConnectionApplyConfiguration {
	b.TrunkPort = value
	return b
}
