// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// L2HostConfigApplyConfiguration represents a declarative configuration of the L2HostConfig type for use
// with apply.
//
// L2HostConfig provides node-specific L2 bridge settings.  Different nodes
// may have different bridge types or trunk interface names; each entry
// applies to the nodes matched by its NodeSelector (first-match wins).
type L2HostConfigApplyConfiguration struct {
	// NodeSelector is a Calico selector expression that determines which
	// nodes this configuration applies to.  If omitted, the entry
	// applies to all nodes.  When multiple HostConfig entries are
	// present, the first entry whose selector matches a given node wins;
	// subsequent entries are ignored for that node.
	NodeSelector *string `json:"nodeSelector,omitempty"`
	// Bridge selects the bridge device for these nodes: either a
	// Calico-managed bridge or a pre-existing (BYO) bridge.
	Bridge *L2BridgeDeviceApplyConfiguration `json:"bridge,omitempty"`
	// HostConnections defines how the bridge connects to the physical
	// network on these nodes.  Each entry is a typed connection
	// (currently only trunkPort).  If omitted, no trunk is attached by
	// Calico — the user is responsible for providing external
	// connectivity (e.g. on a BYO bridge with a pre-configured trunk).
	HostConnections []L2HostConnectionApplyConfiguration `json:"hostConnections,omitempty"`
}

// L2HostConfigApplyConfiguration constructs a declarative configuration of the L2HostConfig type for use with
// apply.
func L2HostConfig() *L2HostConfigApplyConfiguration {
	return &L2HostConfigApplyConfiguration{}
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *L2HostConfigApplyConfiguration) WithNodeSelector(value string) *L2HostConfigApplyConfiguration {
	b.NodeSelector = &value
	return b
}

// WithBridge sets the Bridge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bridge field is set to the value of the last call.
func (b *L2HostConfigApplyConfiguration) WithBridge(value *L2BridgeDeviceApplyConfiguration) *L2HostConfigApplyConfiguration {
	b.Bridge = value
	return b
}

// WithHostConnections adds the given value to the HostConnections field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HostConnections field.
func (b *L2HostConfigApplyConfiguration) WithHostConnections(values ...*L2HostConnectionApplyConfiguration) *L2HostConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHostConnections")
		}
		b.HostConnections = append(b.HostConnections, *values[i])
	}
	return b
}
