// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// L2RouteActionApplyConfiguration represents a declarative configuration of the L2RouteAction type for use
// with apply.
//
// L2RouteAction defines the forwarding behaviour for an L2 route.  Exactly
// one field must be set.
type L2RouteActionApplyConfiguration struct {
	// NextHop forwards matching traffic to the specified gateway IP.  The
	// address must be an L2 neighbor on this subnet, reachable via the
	// bridge; the route is installed onlink.
	NextHop *string `json:"nextHop,omitempty"`
}

// L2RouteActionApplyConfiguration constructs a declarative configuration of the L2RouteAction type for use with
// apply.
func L2RouteAction() *L2RouteActionApplyConfiguration {
	return &L2RouteActionApplyConfiguration{}
}

// WithNextHop sets the NextHop field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextHop field is set to the value of the last call.
func (b *L2RouteActionApplyConfiguration) WithNextHop(value string) *L2RouteActionApplyConfiguration {
	b.NextHop = &value
	return b
}
