// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// L2VLANMatchApplyConfiguration represents a declarative configuration of the L2VLANMatch type for use
// with apply.
//
// L2VLANMatch identifies a VLAN segment.  Exactly one field must be set.
type L2VLANMatchApplyConfiguration struct {
	// ID selects a single 802.1Q VLAN (1-4094).
	ID *uint16 `json:"id,omitempty"`
	// Range selects a contiguous range of VLAN IDs (inclusive).
	Range *L2VLANRangeApplyConfiguration `json:"range,omitempty"`
}

// L2VLANMatchApplyConfiguration constructs a declarative configuration of the L2VLANMatch type for use with
// apply.
func L2VLANMatch() *L2VLANMatchApplyConfiguration {
	return &L2VLANMatchApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *L2VLANMatchApplyConfiguration) WithID(value uint16) *L2VLANMatchApplyConfiguration {
	b.ID = &value
	return b
}

// WithRange sets the Range field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Range field is set to the value of the last call.
func (b *L2VLANMatchApplyConfiguration) WithRange(value *L2VLANRangeApplyConfiguration) *L2VLANMatchApplyConfiguration {
	b.Range = value
	return b
}
