// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// NetworkSubnetStatusApplyConfiguration represents a declarative configuration of the NetworkSubnetStatus type for use
// with apply.
//
// NetworkSubnetStatus reports which IP pools serve one subnet of an L2 network.
type NetworkSubnetStatusApplyConfiguration struct {
	// CIDR is the subnet as written in spec.l2Bridge.vlans[].subnets[].cidr.
	CIDR *string `json:"cidr,omitempty"`
	// Pools names the L2Workload IP pools whose CIDR is equal to or narrower than this subnet,
	// which are the pools IPAM considers for it. Empty means workloads on this subnet get no address.
	Pools []string `json:"pools,omitempty"`
}

// NetworkSubnetStatusApplyConfiguration constructs a declarative configuration of the NetworkSubnetStatus type for use with
// apply.
func NetworkSubnetStatus() *NetworkSubnetStatusApplyConfiguration {
	return &NetworkSubnetStatusApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *NetworkSubnetStatusApplyConfiguration) WithCIDR(value string) *NetworkSubnetStatusApplyConfiguration {
	b.CIDR = &value
	return b
}

// WithPools adds the given value to the Pools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pools field.
func (b *NetworkSubnetStatusApplyConfiguration) WithPools(values ...string) *NetworkSubnetStatusApplyConfiguration {
	for i := range values {
		b.Pools = append(b.Pools, values[i])
	}
	return b
}
