// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
)

// PacketCaptureFileApplyConfiguration represents a declarative configuration of the PacketCaptureFile type for use
// with apply.
//
// PacketCaptureFile describes files generated by a PacketCapture. It describes the location of the packet capture files
// that is identified via a node, its directory and the file names generated.
type PacketCaptureFileApplyConfiguration struct {
	// Node identifies with a physical node from the cluster via its hostname
	Node *string `json:"node,omitempty"`
	// Directory represents the path inside the calico-node container for the the generated files
	Directory *string `json:"directory,omitempty"`
	// FileNames represents the name of the generated file for a PacketCapture ordered alphanumerically.
	// The active packet capture file will be identified using the following schema:
	// "{workload endpoint name}_{host network interface}.pcap" .
	// Rotated capture files name will contain an index matching the rotation timestamp.
	FileNames []string                            `json:"fileNames,omitempty"`
	State     *projectcalicov3.PacketCaptureState `json:"state,omitempty"`
}

// PacketCaptureFileApplyConfiguration constructs a declarative configuration of the PacketCaptureFile type for use with
// apply.
func PacketCaptureFile() *PacketCaptureFileApplyConfiguration {
	return &PacketCaptureFileApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *PacketCaptureFileApplyConfiguration) WithNode(value string) *PacketCaptureFileApplyConfiguration {
	b.Node = &value
	return b
}

// WithDirectory sets the Directory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Directory field is set to the value of the last call.
func (b *PacketCaptureFileApplyConfiguration) WithDirectory(value string) *PacketCaptureFileApplyConfiguration {
	b.Directory = &value
	return b
}

// WithFileNames adds the given value to the FileNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FileNames field.
func (b *PacketCaptureFileApplyConfiguration) WithFileNames(values ...string) *PacketCaptureFileApplyConfiguration {
	for i := range values {
		b.FileNames = append(b.FileNames, values[i])
	}
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *PacketCaptureFileApplyConfiguration) WithState(value projectcalicov3.PacketCaptureState) *PacketCaptureFileApplyConfiguration {
	b.State = &value
	return b
}
