// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PolicyRecommendationScopeSpecApplyConfiguration represents a declarative configuration of the PolicyRecommendationScopeSpec type for use
// with apply.
type PolicyRecommendationScopeSpecApplyConfiguration struct {
	// How frequently to run the recommendation engine to create and refine recommended policies.
	// [Default: 150s]
	Interval *v1.Duration `json:"interval,omitempty"`
	// How far back to look in flow logs when first creating a recommended policy.
	// [Default: 24h]
	InitialLookback *v1.Duration `json:"initialLookback,omitempty"`
	// StabilizationPeriod is the amount of time a recommended policy should remain unchanged to be
	// deemed stable and ready to be enforced.
	// [Default: 10m]
	StabilizationPeriod *v1.Duration `json:"stabilizationPeriod,omitempty"`
	// The maximum number of rules that are permitted in the ingress or egress set. For egress rules,
	// any egress domain rules will be simplified by contracting all domains into a single egress
	// domain NetworkSet. If the number of rules exceeds this limit, the recommendation engine will
	// treat this as an error condition.
	// [Default: 20]
	MaxRules *int `json:"maxRules,omitempty"`
	// The number of staged policies that are actively learning at any one time, after which the
	// policy recommendation engine will stop adding new recommendations.
	// [Default: 20]
	PoliciesLearningCutOff *int `json:"policiesLearningCutOff,omitempty"`
	// The namespace spec contains the namespace relative recommendation vars.
	NamespaceSpec *PolicyRecommendationScopeNamespaceSpecApplyConfiguration `json:"namespaceSpec,omitempty"`
	// The host endpoint spec contains host endpoint relative recommendation vars.
	HostEndpointSpec *PolicyRecommendationScopeHostEndpointSpecApplyConfiguration `json:"hostEndpointSpec,omitempty"`
}

// PolicyRecommendationScopeSpecApplyConfiguration constructs a declarative configuration of the PolicyRecommendationScopeSpec type for use with
// apply.
func PolicyRecommendationScopeSpec() *PolicyRecommendationScopeSpecApplyConfiguration {
	return &PolicyRecommendationScopeSpecApplyConfiguration{}
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *PolicyRecommendationScopeSpecApplyConfiguration) WithInterval(value v1.Duration) *PolicyRecommendationScopeSpecApplyConfiguration {
	b.Interval = &value
	return b
}

// WithInitialLookback sets the InitialLookback field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialLookback field is set to the value of the last call.
func (b *PolicyRecommendationScopeSpecApplyConfiguration) WithInitialLookback(value v1.Duration) *PolicyRecommendationScopeSpecApplyConfiguration {
	b.InitialLookback = &value
	return b
}

// WithStabilizationPeriod sets the StabilizationPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StabilizationPeriod field is set to the value of the last call.
func (b *PolicyRecommendationScopeSpecApplyConfiguration) WithStabilizationPeriod(value v1.Duration) *PolicyRecommendationScopeSpecApplyConfiguration {
	b.StabilizationPeriod = &value
	return b
}

// WithMaxRules sets the MaxRules field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRules field is set to the value of the last call.
func (b *PolicyRecommendationScopeSpecApplyConfiguration) WithMaxRules(value int) *PolicyRecommendationScopeSpecApplyConfiguration {
	b.MaxRules = &value
	return b
}

// WithPoliciesLearningCutOff sets the PoliciesLearningCutOff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoliciesLearningCutOff field is set to the value of the last call.
func (b *PolicyRecommendationScopeSpecApplyConfiguration) WithPoliciesLearningCutOff(value int) *PolicyRecommendationScopeSpecApplyConfiguration {
	b.PoliciesLearningCutOff = &value
	return b
}

// WithNamespaceSpec sets the NamespaceSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSpec field is set to the value of the last call.
func (b *PolicyRecommendationScopeSpecApplyConfiguration) WithNamespaceSpec(value *PolicyRecommendationScopeNamespaceSpecApplyConfiguration) *PolicyRecommendationScopeSpecApplyConfiguration {
	b.NamespaceSpec = value
	return b
}

// WithHostEndpointSpec sets the HostEndpointSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostEndpointSpec field is set to the value of the last call.
func (b *PolicyRecommendationScopeSpecApplyConfiguration) WithHostEndpointSpec(value *PolicyRecommendationScopeHostEndpointSpecApplyConfiguration) *PolicyRecommendationScopeSpecApplyConfiguration {
	b.HostEndpointSpec = value
	return b
}
