// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// ReportStatusApplyConfiguration represents a declarative configuration of the ReportStatus type for use
// with apply.
//
// ReportStatus contains the status of the automated report generation.
type ReportStatusApplyConfiguration struct {
	// The configured report jobs that have completed successfully.
	LastSuccessfulReportJobs []CompletedReportJobApplyConfiguration `json:"lastSuccessfulReportJobs,omitempty"`
	// The configured report jobs that have failed.
	LastFailedReportJobs []CompletedReportJobApplyConfiguration `json:"lastFailedReportJobs,omitempty"`
	// The set of active report jobs.
	ActiveReportJobs []ReportJobApplyConfiguration `json:"activeReportJobs,omitempty"`
	// The last scheduled report job.
	LastScheduledReportJob *ReportJobApplyConfiguration `json:"lastScheduledReportJob,omitempty"`
}

// ReportStatusApplyConfiguration constructs a declarative configuration of the ReportStatus type for use with
// apply.
func ReportStatus() *ReportStatusApplyConfiguration {
	return &ReportStatusApplyConfiguration{}
}

// WithLastSuccessfulReportJobs adds the given value to the LastSuccessfulReportJobs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LastSuccessfulReportJobs field.
func (b *ReportStatusApplyConfiguration) WithLastSuccessfulReportJobs(values ...*CompletedReportJobApplyConfiguration) *ReportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithLastSuccessfulReportJobs")
		}
		b.LastSuccessfulReportJobs = append(b.LastSuccessfulReportJobs, *values[i])
	}
	return b
}

// WithLastFailedReportJobs adds the given value to the LastFailedReportJobs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LastFailedReportJobs field.
func (b *ReportStatusApplyConfiguration) WithLastFailedReportJobs(values ...*CompletedReportJobApplyConfiguration) *ReportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithLastFailedReportJobs")
		}
		b.LastFailedReportJobs = append(b.LastFailedReportJobs, *values[i])
	}
	return b
}

// WithActiveReportJobs adds the given value to the ActiveReportJobs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveReportJobs field.
func (b *ReportStatusApplyConfiguration) WithActiveReportJobs(values ...*ReportJobApplyConfiguration) *ReportStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActiveReportJobs")
		}
		b.ActiveReportJobs = append(b.ActiveReportJobs, *values[i])
	}
	return b
}

// WithLastScheduledReportJob sets the LastScheduledReportJob field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScheduledReportJob field is set to the value of the last call.
func (b *ReportStatusApplyConfiguration) WithLastScheduledReportJob(value *ReportJobApplyConfiguration) *ReportStatusApplyConfiguration {
	b.LastScheduledReportJob = value
	return b
}
