// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// SecurityEventWebhookConfigVarApplyConfiguration represents a declarative configuration of the SecurityEventWebhookConfigVar type for use
// with apply.
type SecurityEventWebhookConfigVarApplyConfiguration struct {
	Name      *string                                                `json:"name,omitempty"`
	Value     *string                                                `json:"value,omitempty"`
	ValueFrom *SecurityEventWebhookConfigVarSourceApplyConfiguration `json:"valueFrom,omitempty"`
}

// SecurityEventWebhookConfigVarApplyConfiguration constructs a declarative configuration of the SecurityEventWebhookConfigVar type for use with
// apply.
func SecurityEventWebhookConfigVar() *SecurityEventWebhookConfigVarApplyConfiguration {
	return &SecurityEventWebhookConfigVarApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SecurityEventWebhookConfigVarApplyConfiguration) WithName(value string) *SecurityEventWebhookConfigVarApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *SecurityEventWebhookConfigVarApplyConfiguration) WithValue(value string) *SecurityEventWebhookConfigVarApplyConfiguration {
	b.Value = &value
	return b
}

// WithValueFrom sets the ValueFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueFrom field is set to the value of the last call.
func (b *SecurityEventWebhookConfigVarApplyConfiguration) WithValueFrom(value *SecurityEventWebhookConfigVarSourceApplyConfiguration) *SecurityEventWebhookConfigVarApplyConfiguration {
	b.ValueFrom = value
	return b
}
