// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// UISettingsGroupSpecApplyConfiguration represents a declarative configuration of the UISettingsGroupSpec type for use
// with apply.
//
// UISettingsGroupSpec contains the specification for a UISettingsGroup resource.
type UISettingsGroupSpecApplyConfiguration struct {
	// This description is displayed by the UI when asking where to store any UI-specific settings
	// such as views, layers, dashboards etc. This name should be a short description that relates
	// the settings to the set of clusters defined below, the set of users or groups that are able to
	// access to these settings (defined via RBAC) or the set of applications common to the set of
	// users or groups that can access these settings.
	// Examples might be:
	// - "cluster" when these settings apply to the whole cluster
	// - "global" when these settings apply to all clusters (in an Multi-Cluster environment)
	// - "security team" if these settings are accessible only to the security group and therefore
	// applicable to the applications accessible by that team
	// - "storefront" if these settings are accessible to all users and groups that can access the
	// storefront set of applications
	// - "user" if these settings are accessible to only a single user
	Description *string `json:"description,omitempty"`
	// The type of filter to use when listing and watching the UISettings associated with this group. If set to None
	// a List/watch of UISettings in this group will return all UISettings. If set to User a list/watch of UISettings
	// in this group will return only UISettings created by the user making the request.
	// For settings groups that are specific to users and where multiple users may access the settings in this group
	// we recommend setting this to "User" to avoid cluttering up the UI with settings for other users.
	// Note this is only a filter. Full lockdown of UISettings for specific users should be handled using appropriate
	// RBAC.
	FilterType *string `json:"filterType,omitempty"`
}

// UISettingsGroupSpecApplyConfiguration constructs a declarative configuration of the UISettingsGroupSpec type for use with
// apply.
func UISettingsGroupSpec() *UISettingsGroupSpecApplyConfiguration {
	return &UISettingsGroupSpecApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *UISettingsGroupSpecApplyConfiguration) WithDescription(value string) *UISettingsGroupSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithFilterType sets the FilterType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FilterType field is set to the value of the last call.
func (b *UISettingsGroupSpecApplyConfiguration) WithFilterType(value string) *UISettingsGroupSpecApplyConfiguration {
	b.FilterType = &value
	return b
}
