// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// VRFNetworkSpecApplyConfiguration represents a declarative configuration of the VRFNetworkSpec type for use
// with apply.
//
// VRFNetworkSpec configures a VRF-based network that isolates pods in a Linux VRF.
type VRFNetworkSpecApplyConfiguration struct {
	// Routing controls cluster-wide routing behaviour for this VRF network.
	Routing *VRFRoutingApplyConfiguration `json:"routing,omitempty"`
	// HostConfig defines per-node configuration for this VRF network.  At least one entry
	// must be specified.  When multiple entries are present (e.g. one per rack), they must
	// have disjoint nodeSelectors although this is not enforced.  For a given node, the
	// first matching entry is applied and all others are ignored.
	//
	// The list is stored and served as a JSON array; Kubernetes preserves the
	// order in which entries were submitted (including across Server-Side
	// Apply merges keyed on nodeSelector), so the result of `kubectl get -oyaml`
	// is authoritative for "first match wins".  Single-actor edits keep the
	// order users see in the YAML they edit.
	HostConfig []VRFHostConfigApplyConfiguration `json:"hostConfig,omitempty"`
}

// VRFNetworkSpecApplyConfiguration constructs a declarative configuration of the VRFNetworkSpec type for use with
// apply.
func VRFNetworkSpec() *VRFNetworkSpecApplyConfiguration {
	return &VRFNetworkSpecApplyConfiguration{}
}

// WithRouting sets the Routing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Routing field is set to the value of the last call.
func (b *VRFNetworkSpecApplyConfiguration) WithRouting(value *VRFRoutingApplyConfiguration) *VRFNetworkSpecApplyConfiguration {
	b.Routing = value
	return b
}

// WithHostConfig adds the given value to the HostConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HostConfig field.
func (b *VRFNetworkSpecApplyConfiguration) WithHostConfig(values ...*VRFHostConfigApplyConfiguration) *VRFNetworkSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHostConfig")
		}
		b.HostConfig = append(b.HostConfig, *values[i])
	}
	return b
}
