// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
)

// VRFRoutingApplyConfiguration represents a declarative configuration of the VRFRouting type for use
// with apply.
//
// VRFRouting holds cluster-wide routing settings for a VRF network.
type VRFRoutingApplyConfiguration struct {
	// InClusterMode controls how Felix programs routes to pods on remote nodes inside
	// the VRF routing table.
	//
	// - Local: Felix programs routes to VRF pods local to this node;
	// routing to pods on other nodes must be handled by BGP.
	InClusterMode *projectcalicov3.InClusterRoutingMode `json:"inClusterMode,omitempty"`
}

// VRFRoutingApplyConfiguration constructs a declarative configuration of the VRFRouting type for use with
// apply.
func VRFRouting() *VRFRoutingApplyConfiguration {
	return &VRFRoutingApplyConfiguration{}
}

// WithInClusterMode sets the InClusterMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InClusterMode field is set to the value of the last call.
func (b *VRFRoutingApplyConfiguration) WithInClusterMode(value projectcalicov3.InClusterRoutingMode) *VRFRoutingApplyConfiguration {
	b.InClusterMode = &value
	return b
}
