// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	projectcalicov3 "github.com/tigera/api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeUISettings implements UISettingsInterface
type fakeUISettings struct {
	*gentype.FakeClientWithList[*v3.UISettings, *v3.UISettingsList]
	Fake *FakeProjectcalicoV3
}

func newFakeUISettings(fake *FakeProjectcalicoV3) projectcalicov3.UISettingsInterface {
	return &fakeUISettings{
		gentype.NewFakeClientWithList[*v3.UISettings, *v3.UISettingsList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("uisettings"),
			v3.SchemeGroupVersion.WithKind("UISettings"),
			func() *v3.UISettings { return &v3.UISettings{} },
			func() *v3.UISettingsList { return &v3.UISettingsList{} },
			func(dst, src *v3.UISettingsList) { dst.ListMeta = src.ListMeta },
			func(list *v3.UISettingsList) []*v3.UISettings { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.UISettingsList, items []*v3.UISettings) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
