// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	projectcalicov3 "github.com/tigera/api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakePolicyRecommendationScopes implements PolicyRecommendationScopeInterface
type fakePolicyRecommendationScopes struct {
	*gentype.FakeClientWithList[*v3.PolicyRecommendationScope, *v3.PolicyRecommendationScopeList]
	Fake *FakeProjectcalicoV3
}

func newFakePolicyRecommendationScopes(fake *FakeProjectcalicoV3) projectcalicov3.PolicyRecommendationScopeInterface {
	return &fakePolicyRecommendationScopes{
		gentype.NewFakeClientWithList[*v3.PolicyRecommendationScope, *v3.PolicyRecommendationScopeList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("policyrecommendationscopes"),
			v3.SchemeGroupVersion.WithKind("PolicyRecommendationScope"),
			func() *v3.PolicyRecommendationScope { return &v3.PolicyRecommendationScope{} },
			func() *v3.PolicyRecommendationScopeList { return &v3.PolicyRecommendationScopeList{} },
			func(dst, src *v3.PolicyRecommendationScopeList) { dst.ListMeta = src.ListMeta },
			func(list *v3.PolicyRecommendationScopeList) []*v3.PolicyRecommendationScope {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.PolicyRecommendationScopeList, items []*v3.PolicyRecommendationScope) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
