// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	projectcalicov3 "github.com/tigera/api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeManagedClusters implements ManagedClusterInterface
type fakeManagedClusters struct {
	*gentype.FakeClientWithList[*v3.ManagedCluster, *v3.ManagedClusterList]
	Fake *FakeProjectcalicoV3
}

func newFakeManagedClusters(fake *FakeProjectcalicoV3) projectcalicov3.ManagedClusterInterface {
	return &fakeManagedClusters{
		gentype.NewFakeClientWithList[*v3.ManagedCluster, *v3.ManagedClusterList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("managedclusters"),
			v3.SchemeGroupVersion.WithKind("ManagedCluster"),
			func() *v3.ManagedCluster { return &v3.ManagedCluster{} },
			func() *v3.ManagedClusterList { return &v3.ManagedClusterList{} },
			func(dst, src *v3.ManagedClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ManagedClusterList) []*v3.ManagedCluster { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.ManagedClusterList, items []*v3.ManagedCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
