// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	applyconfigurationgeneratedprojectcalicov3 "github.com/tigera/api/pkg/client/applyconfiguration_generated/projectcalico/v3"
	scheme "github.com/tigera/api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BFDConfigurationsGetter has a method to return a BFDConfigurationInterface.
// A group's client should implement this interface.
type BFDConfigurationsGetter interface {
	BFDConfigurations() BFDConfigurationInterface
}

// BFDConfigurationInterface has methods to work with BFDConfiguration resources.
type BFDConfigurationInterface interface {
	Create(ctx context.Context, bFDConfiguration *projectcalicov3.BFDConfiguration, opts v1.CreateOptions) (*projectcalicov3.BFDConfiguration, error)
	Update(ctx context.Context, bFDConfiguration *projectcalicov3.BFDConfiguration, opts v1.UpdateOptions) (*projectcalicov3.BFDConfiguration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*projectcalicov3.BFDConfiguration, error)
	List(ctx context.Context, opts v1.ListOptions) (*projectcalicov3.BFDConfigurationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *projectcalicov3.BFDConfiguration, err error)
	Apply(ctx context.Context, bFDConfiguration *applyconfigurationgeneratedprojectcalicov3.BFDConfigurationApplyConfiguration, opts v1.ApplyOptions) (result *projectcalicov3.BFDConfiguration, err error)
	BFDConfigurationExpansion
}

// bFDConfigurations implements BFDConfigurationInterface
type bFDConfigurations struct {
	*gentype.ClientWithListAndApply[*projectcalicov3.BFDConfiguration, *projectcalicov3.BFDConfigurationList, *applyconfigurationgeneratedprojectcalicov3.BFDConfigurationApplyConfiguration]
}

// newBFDConfigurations returns a BFDConfigurations
func newBFDConfigurations(c *ProjectcalicoV3Client) *bFDConfigurations {
	return &bFDConfigurations{
		gentype.NewClientWithListAndApply[*projectcalicov3.BFDConfiguration, *projectcalicov3.BFDConfigurationList, *applyconfigurationgeneratedprojectcalicov3.BFDConfigurationApplyConfiguration](
			"bfdconfigurations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *projectcalicov3.BFDConfiguration { return &projectcalicov3.BFDConfiguration{} },
			func() *projectcalicov3.BFDConfigurationList { return &projectcalicov3.BFDConfigurationList{} },
		),
	}
}
