// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	scheme "github.com/tigera/api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GlobalAlertTemplatesGetter has a method to return a GlobalAlertTemplateInterface.
// A group's client should implement this interface.
type GlobalAlertTemplatesGetter interface {
	GlobalAlertTemplates() GlobalAlertTemplateInterface
}

// GlobalAlertTemplateInterface has methods to work with GlobalAlertTemplate resources.
type GlobalAlertTemplateInterface interface {
	Create(ctx context.Context, globalAlertTemplate *projectcalicov3.GlobalAlertTemplate, opts v1.CreateOptions) (*projectcalicov3.GlobalAlertTemplate, error)
	Update(ctx context.Context, globalAlertTemplate *projectcalicov3.GlobalAlertTemplate, opts v1.UpdateOptions) (*projectcalicov3.GlobalAlertTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*projectcalicov3.GlobalAlertTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*projectcalicov3.GlobalAlertTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *projectcalicov3.GlobalAlertTemplate, err error)
	GlobalAlertTemplateExpansion
}

// globalAlertTemplates implements GlobalAlertTemplateInterface
type globalAlertTemplates struct {
	*gentype.ClientWithList[*projectcalicov3.GlobalAlertTemplate, *projectcalicov3.GlobalAlertTemplateList]
}

// newGlobalAlertTemplates returns a GlobalAlertTemplates
func newGlobalAlertTemplates(c *ProjectcalicoV3Client) *globalAlertTemplates {
	return &globalAlertTemplates{
		gentype.NewClientWithList[*projectcalicov3.GlobalAlertTemplate, *projectcalicov3.GlobalAlertTemplateList](
			"globalalerttemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *projectcalicov3.GlobalAlertTemplate { return &projectcalicov3.GlobalAlertTemplate{} },
			func() *projectcalicov3.GlobalAlertTemplateList { return &projectcalicov3.GlobalAlertTemplateList{} },
		),
	}
}
