// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	applyconfigurationgeneratedprojectcalicov3 "github.com/tigera/api/pkg/client/applyconfiguration_generated/projectcalico/v3"
	scheme "github.com/tigera/api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ManagedClustersGetter has a method to return a ManagedClusterInterface.
// A group's client should implement this interface.
type ManagedClustersGetter interface {
	ManagedClusters() ManagedClusterInterface
}

// ManagedClusterInterface has methods to work with ManagedCluster resources.
type ManagedClusterInterface interface {
	Create(ctx context.Context, managedCluster *projectcalicov3.ManagedCluster, opts v1.CreateOptions) (*projectcalicov3.ManagedCluster, error)
	Update(ctx context.Context, managedCluster *projectcalicov3.ManagedCluster, opts v1.UpdateOptions) (*projectcalicov3.ManagedCluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, managedCluster *projectcalicov3.ManagedCluster, opts v1.UpdateOptions) (*projectcalicov3.ManagedCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*projectcalicov3.ManagedCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*projectcalicov3.ManagedClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *projectcalicov3.ManagedCluster, err error)
	Apply(ctx context.Context, managedCluster *applyconfigurationgeneratedprojectcalicov3.ManagedClusterApplyConfiguration, opts v1.ApplyOptions) (result *projectcalicov3.ManagedCluster, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, managedCluster *applyconfigurationgeneratedprojectcalicov3.ManagedClusterApplyConfiguration, opts v1.ApplyOptions) (result *projectcalicov3.ManagedCluster, err error)
	ManagedClusterExpansion
}

// managedClusters implements ManagedClusterInterface
type managedClusters struct {
	*gentype.ClientWithListAndApply[*projectcalicov3.ManagedCluster, *projectcalicov3.ManagedClusterList, *applyconfigurationgeneratedprojectcalicov3.ManagedClusterApplyConfiguration]
}

// newManagedClusters returns a ManagedClusters
func newManagedClusters(c *ProjectcalicoV3Client) *managedClusters {
	return &managedClusters{
		gentype.NewClientWithListAndApply[*projectcalicov3.ManagedCluster, *projectcalicov3.ManagedClusterList, *applyconfigurationgeneratedprojectcalicov3.ManagedClusterApplyConfiguration](
			"managedclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *projectcalicov3.ManagedCluster { return &projectcalicov3.ManagedCluster{} },
			func() *projectcalicov3.ManagedClusterList { return &projectcalicov3.ManagedClusterList{} },
		),
	}
}
