// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"context"
	"time"

	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	scheme "github.com/tigera/api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UISettingsesGetter has a method to return a UISettingsInterface.
// A group's client should implement this interface.
type UISettingsesGetter interface {
	UISettingses(namespace string) UISettingsInterface
}

// UISettingsInterface has methods to work with UISettings resources.
type UISettingsInterface interface {
	Create(ctx context.Context, uISettings *v3.UISettings, opts v1.CreateOptions) (*v3.UISettings, error)
	Update(ctx context.Context, uISettings *v3.UISettings, opts v1.UpdateOptions) (*v3.UISettings, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v3.UISettings, error)
	List(ctx context.Context, opts v1.ListOptions) (*v3.UISettingsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.UISettings, err error)
	UISettingsExpansion
}

// uISettingses implements UISettingsInterface
type uISettingses struct {
	client rest.Interface
	ns     string
}

// newUISettingses returns a UISettingses
func newUISettingses(c *ProjectcalicoV3Client, namespace string) *uISettingses {
	return &uISettingses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the uISettings, and returns the corresponding uISettings object, and an error if there is any.
func (c *uISettingses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v3.UISettings, err error) {
	result = &v3.UISettings{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("uisettingses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UISettingses that match those selectors.
func (c *uISettingses) List(ctx context.Context, opts v1.ListOptions) (result *v3.UISettingsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v3.UISettingsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("uisettingses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested uISettingses.
func (c *uISettingses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("uisettingses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a uISettings and creates it.  Returns the server's representation of the uISettings, and an error, if there is any.
func (c *uISettingses) Create(ctx context.Context, uISettings *v3.UISettings, opts v1.CreateOptions) (result *v3.UISettings, err error) {
	result = &v3.UISettings{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("uisettingses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(uISettings).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a uISettings and updates it. Returns the server's representation of the uISettings, and an error, if there is any.
func (c *uISettingses) Update(ctx context.Context, uISettings *v3.UISettings, opts v1.UpdateOptions) (result *v3.UISettings, err error) {
	result = &v3.UISettings{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("uisettingses").
		Name(uISettings.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(uISettings).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the uISettings and deletes it. Returns an error if one occurs.
func (c *uISettingses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("uisettingses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *uISettingses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("uisettingses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched uISettings.
func (c *uISettingses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.UISettings, err error) {
	result = &v3.UISettings{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("uisettingses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
