// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AuthorizationReviewLister helps list AuthorizationReviews.
// All objects returned here must be treated as read-only.
type AuthorizationReviewLister interface {
	// List lists all AuthorizationReviews in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v3.AuthorizationReview, err error)
	// Get retrieves the AuthorizationReview from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v3.AuthorizationReview, error)
	AuthorizationReviewListerExpansion
}

// authorizationReviewLister implements the AuthorizationReviewLister interface.
type authorizationReviewLister struct {
	indexer cache.Indexer
}

// NewAuthorizationReviewLister returns a new AuthorizationReviewLister.
func NewAuthorizationReviewLister(indexer cache.Indexer) AuthorizationReviewLister {
	return &authorizationReviewLister{indexer: indexer}
}

// List lists all AuthorizationReviews in the indexer.
func (s *authorizationReviewLister) List(selector labels.Selector) (ret []*v3.AuthorizationReview, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v3.AuthorizationReview))
	})
	return ret, err
}

// Get retrieves the AuthorizationReview from the index for a given name.
func (s *authorizationReviewLister) Get(name string) (*v3.AuthorizationReview, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v3.Resource("authorizationreview"), name)
	}
	return obj.(*v3.AuthorizationReview), nil
}
