// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkLister helps list Networks.
// All objects returned here must be treated as read-only.
type NetworkLister interface {
	// List lists all Networks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalicov3.Network, err error)
	// Get retrieves the Network from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*projectcalicov3.Network, error)
	NetworkListerExpansion
}

// networkLister implements the NetworkLister interface.
type networkLister struct {
	listers.ResourceIndexer[*projectcalicov3.Network]
}

// NewNetworkLister returns a new NetworkLister.
func NewNetworkLister(indexer cache.Indexer) NetworkLister {
	return &networkLister{listers.New[*projectcalicov3.Network](indexer, projectcalicov3.Resource("network"))}
}
