// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// UISettingsLister helps list UISettings.
// All objects returned here must be treated as read-only.
type UISettingsLister interface {
	// List lists all UISettings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalicov3.UISettings, err error)
	// Get retrieves the UISettings from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*projectcalicov3.UISettings, error)
	UISettingsListerExpansion
}

// uISettingsLister implements the UISettingsLister interface.
type uISettingsLister struct {
	listers.ResourceIndexer[*projectcalicov3.UISettings]
}

// NewUISettingsLister returns a new UISettingsLister.
func NewUISettingsLister(indexer cache.Indexer) UISettingsLister {
	return &uISettingsLister{listers.New[*projectcalicov3.UISettings](indexer, projectcalicov3.Resource("uisettings"))}
}
