// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// UISettingsGroupLister helps list UISettingsGroups.
// All objects returned here must be treated as read-only.
type UISettingsGroupLister interface {
	// List lists all UISettingsGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v3.UISettingsGroup, err error)
	// Get retrieves the UISettingsGroup from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v3.UISettingsGroup, error)
	UISettingsGroupListerExpansion
}

// uISettingsGroupLister implements the UISettingsGroupLister interface.
type uISettingsGroupLister struct {
	indexer cache.Indexer
}

// NewUISettingsGroupLister returns a new UISettingsGroupLister.
func NewUISettingsGroupLister(indexer cache.Indexer) UISettingsGroupLister {
	return &uISettingsGroupLister{indexer: indexer}
}

// List lists all UISettingsGroups in the indexer.
func (s *uISettingsGroupLister) List(selector labels.Selector) (ret []*v3.UISettingsGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v3.UISettingsGroup))
	})
	return ret, err
}

// Get retrieves the UISettingsGroup from the index for a given name.
func (s *uISettingsGroupLister) Get(name string) (*v3.UISettingsGroup, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v3.Resource("uisettingsgroup"), name)
	}
	return obj.(*v3.UISettingsGroup), nil
}
