// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by informer-gen. DO NOT EDIT.

package v3

import (
	"context"
	time "time"

	projectcalicov3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	clientset "github.com/tigera/api/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/tigera/api/pkg/client/informers_generated/externalversions/internalinterfaces"
	v3 "github.com/tigera/api/pkg/client/listers_generated/projectcalico/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeepPacketInspectionInformer provides access to a shared informer and lister for
// DeepPacketInspections.
type DeepPacketInspectionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v3.DeepPacketInspectionLister
}

type deepPacketInspectionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeepPacketInspectionInformer constructs a new informer for DeepPacketInspection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeepPacketInspectionInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeepPacketInspectionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeepPacketInspectionInformer constructs a new informer for DeepPacketInspection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeepPacketInspectionInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProjectcalicoV3().DeepPacketInspections(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProjectcalicoV3().DeepPacketInspections(namespace).Watch(context.TODO(), options)
			},
		},
		&projectcalicov3.DeepPacketInspection{},
		resyncPeriod,
		indexers,
	)
}

func (f *deepPacketInspectionInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeepPacketInspectionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deepPacketInspectionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&projectcalicov3.DeepPacketInspection{}, f.defaultInformer)
}

func (f *deepPacketInspectionInformer) Lister() v3.DeepPacketInspectionLister {
	return v3.NewDeepPacketInspectionLister(f.Informer().GetIndexer())
}
