// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by informer-gen. DO NOT EDIT.

package v3

import (
	internalinterfaces "github.com/tigera/api/pkg/client/informers_generated/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AlertExceptions returns a AlertExceptionInformer.
	AlertExceptions() TypedAlertExceptionInformer
	// AuthorizationReviews returns a AuthorizationReviewInformer.
	AuthorizationReviews() TypedAuthorizationReviewInformer
	// BFDConfigurations returns a BFDConfigurationInformer.
	BFDConfigurations() TypedBFDConfigurationInformer
	// BGPConfigurations returns a BGPConfigurationInformer.
	BGPConfigurations() TypedBGPConfigurationInformer
	// BGPFilters returns a BGPFilterInformer.
	BGPFilters() TypedBGPFilterInformer
	// BGPPeers returns a BGPPeerInformer.
	BGPPeers() TypedBGPPeerInformer
	// BlockAffinities returns a BlockAffinityInformer.
	BlockAffinities() TypedBlockAffinityInformer
	// CalicoNodeStatuses returns a CalicoNodeStatusInformer.
	CalicoNodeStatuses() TypedCalicoNodeStatusInformer
	// ClusterInformations returns a ClusterInformationInformer.
	ClusterInformations() TypedClusterInformationInformer
	// DeepPacketInspections returns a DeepPacketInspectionInformer.
	DeepPacketInspections() TypedDeepPacketInspectionInformer
	// EgressGatewayPolicies returns a EgressGatewayPolicyInformer.
	EgressGatewayPolicies() TypedEgressGatewayPolicyInformer
	// ExternalNetworks returns a ExternalNetworkInformer.
	ExternalNetworks() TypedExternalNetworkInformer
	// FelixConfigurations returns a FelixConfigurationInformer.
	FelixConfigurations() TypedFelixConfigurationInformer
	// GlobalAlerts returns a GlobalAlertInformer.
	GlobalAlerts() TypedGlobalAlertInformer
	// GlobalAlertTemplates returns a GlobalAlertTemplateInformer.
	GlobalAlertTemplates() TypedGlobalAlertTemplateInformer
	// GlobalNetworkPolicies returns a GlobalNetworkPolicyInformer.
	GlobalNetworkPolicies() TypedGlobalNetworkPolicyInformer
	// GlobalNetworkSets returns a GlobalNetworkSetInformer.
	GlobalNetworkSets() TypedGlobalNetworkSetInformer
	// GlobalReports returns a GlobalReportInformer.
	GlobalReports() TypedGlobalReportInformer
	// GlobalReportTypes returns a GlobalReportTypeInformer.
	GlobalReportTypes() TypedGlobalReportTypeInformer
	// GlobalThreatFeeds returns a GlobalThreatFeedInformer.
	GlobalThreatFeeds() TypedGlobalThreatFeedInformer
	// HostEndpoints returns a HostEndpointInformer.
	HostEndpoints() TypedHostEndpointInformer
	// IPAMBlocks returns a IPAMBlockInformer.
	IPAMBlocks() TypedIPAMBlockInformer
	// IPAMConfigurations returns a IPAMConfigurationInformer.
	IPAMConfigurations() TypedIPAMConfigurationInformer
	// IPAMHandles returns a IPAMHandleInformer.
	IPAMHandles() TypedIPAMHandleInformer
	// IPPools returns a IPPoolInformer.
	IPPools() TypedIPPoolInformer
	// IPReservations returns a IPReservationInformer.
	IPReservations() TypedIPReservationInformer
	// KubeControllersConfigurations returns a KubeControllersConfigurationInformer.
	KubeControllersConfigurations() TypedKubeControllersConfigurationInformer
	// LicenseKeys returns a LicenseKeyInformer.
	LicenseKeys() TypedLicenseKeyInformer
	// ManagedClusters returns a ManagedClusterInformer.
	ManagedClusters() TypedManagedClusterInformer
	// Networks returns a NetworkInformer.
	Networks() TypedNetworkInformer
	// NetworkPolicies returns a NetworkPolicyInformer.
	NetworkPolicies() TypedNetworkPolicyInformer
	// NetworkSets returns a NetworkSetInformer.
	NetworkSets() TypedNetworkSetInformer
	// PacketCaptures returns a PacketCaptureInformer.
	PacketCaptures() TypedPacketCaptureInformer
	// PolicyRecommendationScopes returns a PolicyRecommendationScopeInformer.
	PolicyRecommendationScopes() TypedPolicyRecommendationScopeInformer
	// Profiles returns a ProfileInformer.
	Profiles() TypedProfileInformer
	// RemoteClusterConfigurations returns a RemoteClusterConfigurationInformer.
	RemoteClusterConfigurations() TypedRemoteClusterConfigurationInformer
	// SecurityEventWebhooks returns a SecurityEventWebhookInformer.
	SecurityEventWebhooks() TypedSecurityEventWebhookInformer
	// StagedGlobalNetworkPolicies returns a StagedGlobalNetworkPolicyInformer.
	StagedGlobalNetworkPolicies() TypedStagedGlobalNetworkPolicyInformer
	// StagedKubernetesNetworkPolicies returns a StagedKubernetesNetworkPolicyInformer.
	StagedKubernetesNetworkPolicies() TypedStagedKubernetesNetworkPolicyInformer
	// StagedNetworkPolicies returns a StagedNetworkPolicyInformer.
	StagedNetworkPolicies() TypedStagedNetworkPolicyInformer
	// Tiers returns a TierInformer.
	Tiers() TypedTierInformer
	// UISettings returns a UISettingsInformer.
	UISettings() TypedUISettingsInformer
	// UISettingsGroups returns a UISettingsGroupInformer.
	UISettingsGroups() TypedUISettingsGroupInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AlertExceptions returns a TypedAlertExceptionInformer.
func (v *version) AlertExceptions() TypedAlertExceptionInformer {
	return &alertExceptionInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// AuthorizationReviews returns a TypedAuthorizationReviewInformer.
func (v *version) AuthorizationReviews() TypedAuthorizationReviewInformer {
	return &authorizationReviewInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// BFDConfigurations returns a TypedBFDConfigurationInformer.
func (v *version) BFDConfigurations() TypedBFDConfigurationInformer {
	return &bFDConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// BGPConfigurations returns a TypedBGPConfigurationInformer.
func (v *version) BGPConfigurations() TypedBGPConfigurationInformer {
	return &bGPConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// BGPFilters returns a TypedBGPFilterInformer.
func (v *version) BGPFilters() TypedBGPFilterInformer {
	return &bGPFilterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// BGPPeers returns a TypedBGPPeerInformer.
func (v *version) BGPPeers() TypedBGPPeerInformer {
	return &bGPPeerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// BlockAffinities returns a TypedBlockAffinityInformer.
func (v *version) BlockAffinities() TypedBlockAffinityInformer {
	return &blockAffinityInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// CalicoNodeStatuses returns a TypedCalicoNodeStatusInformer.
func (v *version) CalicoNodeStatuses() TypedCalicoNodeStatusInformer {
	return &calicoNodeStatusInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ClusterInformations returns a TypedClusterInformationInformer.
func (v *version) ClusterInformations() TypedClusterInformationInformer {
	return &clusterInformationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DeepPacketInspections returns a TypedDeepPacketInspectionInformer.
func (v *version) DeepPacketInspections() TypedDeepPacketInspectionInformer {
	return &deepPacketInspectionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EgressGatewayPolicies returns a TypedEgressGatewayPolicyInformer.
func (v *version) EgressGatewayPolicies() TypedEgressGatewayPolicyInformer {
	return &egressGatewayPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ExternalNetworks returns a TypedExternalNetworkInformer.
func (v *version) ExternalNetworks() TypedExternalNetworkInformer {
	return &externalNetworkInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// FelixConfigurations returns a TypedFelixConfigurationInformer.
func (v *version) FelixConfigurations() TypedFelixConfigurationInformer {
	return &felixConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalAlerts returns a TypedGlobalAlertInformer.
func (v *version) GlobalAlerts() TypedGlobalAlertInformer {
	return &globalAlertInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalAlertTemplates returns a TypedGlobalAlertTemplateInformer.
func (v *version) GlobalAlertTemplates() TypedGlobalAlertTemplateInformer {
	return &globalAlertTemplateInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalNetworkPolicies returns a TypedGlobalNetworkPolicyInformer.
func (v *version) GlobalNetworkPolicies() TypedGlobalNetworkPolicyInformer {
	return &globalNetworkPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalNetworkSets returns a TypedGlobalNetworkSetInformer.
func (v *version) GlobalNetworkSets() TypedGlobalNetworkSetInformer {
	return &globalNetworkSetInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalReports returns a TypedGlobalReportInformer.
func (v *version) GlobalReports() TypedGlobalReportInformer {
	return &globalReportInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalReportTypes returns a TypedGlobalReportTypeInformer.
func (v *version) GlobalReportTypes() TypedGlobalReportTypeInformer {
	return &globalReportTypeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalThreatFeeds returns a TypedGlobalThreatFeedInformer.
func (v *version) GlobalThreatFeeds() TypedGlobalThreatFeedInformer {
	return &globalThreatFeedInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// HostEndpoints returns a TypedHostEndpointInformer.
func (v *version) HostEndpoints() TypedHostEndpointInformer {
	return &hostEndpointInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPAMBlocks returns a TypedIPAMBlockInformer.
func (v *version) IPAMBlocks() TypedIPAMBlockInformer {
	return &iPAMBlockInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPAMConfigurations returns a TypedIPAMConfigurationInformer.
func (v *version) IPAMConfigurations() TypedIPAMConfigurationInformer {
	return &iPAMConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPAMHandles returns a TypedIPAMHandleInformer.
func (v *version) IPAMHandles() TypedIPAMHandleInformer {
	return &iPAMHandleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IPPools returns a TypedIPPoolInformer.
func (v *version) IPPools() TypedIPPoolInformer {
	return &iPPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPReservations returns a TypedIPReservationInformer.
func (v *version) IPReservations() TypedIPReservationInformer {
	return &iPReservationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// KubeControllersConfigurations returns a TypedKubeControllersConfigurationInformer.
func (v *version) KubeControllersConfigurations() TypedKubeControllersConfigurationInformer {
	return &kubeControllersConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LicenseKeys returns a TypedLicenseKeyInformer.
func (v *version) LicenseKeys() TypedLicenseKeyInformer {
	return &licenseKeyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ManagedClusters returns a TypedManagedClusterInformer.
func (v *version) ManagedClusters() TypedManagedClusterInformer {
	return &managedClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Networks returns a TypedNetworkInformer.
func (v *version) Networks() TypedNetworkInformer {
	return &networkInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// NetworkPolicies returns a TypedNetworkPolicyInformer.
func (v *version) NetworkPolicies() TypedNetworkPolicyInformer {
	return &networkPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NetworkSets returns a TypedNetworkSetInformer.
func (v *version) NetworkSets() TypedNetworkSetInformer {
	return &networkSetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PacketCaptures returns a TypedPacketCaptureInformer.
func (v *version) PacketCaptures() TypedPacketCaptureInformer {
	return &packetCaptureInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PolicyRecommendationScopes returns a TypedPolicyRecommendationScopeInformer.
func (v *version) PolicyRecommendationScopes() TypedPolicyRecommendationScopeInformer {
	return &policyRecommendationScopeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Profiles returns a TypedProfileInformer.
func (v *version) Profiles() TypedProfileInformer {
	return &profileInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// RemoteClusterConfigurations returns a TypedRemoteClusterConfigurationInformer.
func (v *version) RemoteClusterConfigurations() TypedRemoteClusterConfigurationInformer {
	return &remoteClusterConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// SecurityEventWebhooks returns a TypedSecurityEventWebhookInformer.
func (v *version) SecurityEventWebhooks() TypedSecurityEventWebhookInformer {
	return &securityEventWebhookInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// StagedGlobalNetworkPolicies returns a TypedStagedGlobalNetworkPolicyInformer.
func (v *version) StagedGlobalNetworkPolicies() TypedStagedGlobalNetworkPolicyInformer {
	return &stagedGlobalNetworkPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// StagedKubernetesNetworkPolicies returns a TypedStagedKubernetesNetworkPolicyInformer.
func (v *version) StagedKubernetesNetworkPolicies() TypedStagedKubernetesNetworkPolicyInformer {
	return &stagedKubernetesNetworkPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// StagedNetworkPolicies returns a TypedStagedNetworkPolicyInformer.
func (v *version) StagedNetworkPolicies() TypedStagedNetworkPolicyInformer {
	return &stagedNetworkPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Tiers returns a TypedTierInformer.
func (v *version) Tiers() TypedTierInformer {
	return &tierInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// UISettings returns a TypedUISettingsInformer.
func (v *version) UISettings() TypedUISettingsInformer {
	return &uISettingsInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// UISettingsGroups returns a TypedUISettingsGroupInformer.
func (v *version) UISettingsGroups() TypedUISettingsGroupInformer {
	return &uISettingsGroupInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
